### ISSUE TITLE
記憶體洩漏..?嗎？

### ISSUE THREAD

**Issue by zeroninefourfour** [BrilliantTK/Brilliant#2]
照理來說沒人的MC伺服器(關閉所有插件)只會使用1.5GB左右,可是在BrilliantCore卻使用了3.5GB左右,不懂就問.這感覺不正常
在Linux 4.19測試, OpenJDK 17

**Comment by MagicTeaMC** [comment]
我覺得應該是正常的，因為這個 fork 的功能是刪除 tps 限制
